# use Ganache's forked mainnet mode as the default network
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts v3.0.0
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.0.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.0.0"

networks:
  default: mainnet-fork
  development: 
    cmd_settings: null
  mainnet-fork:
    aave_lending_pool_v2: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
    unirouter: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
    sushirouter: "0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F"
    weth: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    wbtc: "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
    dai: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
    cmd_settings: 
      unlock:
        - 0x06601571AA9D3E8f5f7CDd5b993192618964bAB5
        - 0x218B95BE3ed99141b0144Dba6cE88807c4AD7C09
        - 0x4943b0C9959dcf58871A799dfB71becE0D97c9f4
  kovan:
    aave_lending_pool_v2: "0x88757f2f99175387ab4c6a4b3067c77a695b0349"
    weth: "0xd0a1e359811322d97991e03f863a0c30c2cf029c"
  mainnet:
    aave_lending_pool_v2: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
    weth: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}

dev_deployment_artifacts: true

